site_name: IEETA HPC - User Guides
site_url: https://ieeta-pt.github.io/HPC-guides


nav:
  - Home: index.md
  - About: about.md
  - How to Access: how_to_access.md
  - Quick Start: quick_start.md
  - Detailed Material:
    - Software packages: detail_material/software_packages.md
    - Job management: detail_material/job_management.md
    - Account management: detail_material/account_management.md
  - Deep Learning (GPU) Examples:
    - MNIST example: examples/dl/mnist.md
  - Scientific Computing (CPU) Examples:
    - DNA sequencing: examples/sc/dna.md
    - R: examples/sc/r.md
    
theme: readthedocs

site_author: Tiago Almeida (tiagomeloalmeida@ua.pt)
copyright: Copyright 2023, Pelouro de Infraestrutura - IEETA UA.

